config/routes.rb
Apidog::Engine.routes.draw do
  get "/:api_name/home" => "api#home", :as => "apidog_home"

  get "/:api_name/object/:id" => "api#object", :as => "apidog_object"

end

app/controllers/apidog/api_controller.rb
require_dependency "apidog/application_controller"

module Apidog
  class ApiController < ApplicationController

  	before_filter :load_items

  	def load_items
  		@api = Apidog::Api.find_by_title(params[:api_name])
  		@categories = Apidog::Category.all
  		@methods = Apidog::Action.all
  	end

  	def object 
  		@object = Apidog::Objizzle.find(params[:id])
  	end


  end
end

app/controllers/apidog/application_controller.rb
module Apidog
  class ApplicationController < ActionController::Base
  end
end

app/helpers/apidog/api_helper.rb
module Apidog
  module ApiHelper
  end
end

app/helpers/apidog/application_helper.rb
module Apidog
  module ApplicationHelper
  end
end

app/views/apidog/api/home.html.erb
<h1>Api#home</h1>
<p>Find me in app/views/apidog/api/home.html.erb</p>

app/views/apidog/api/object.html.erb
<h1> <%= @object.name %></h1>

<% @object.actions.each do |meth| %>

	<article>
		<h2> <%= meth.title %> </h2>
		<p class="intro"> <%= meth.subtitle %> </p>
				<div class="url"><span class="method GET">GET</span>
  <%= @api.api_root %><%= meth.path %></div>
		<p>
			<%= meth.description.html_safe %>
		</p>
		

		<div class="highlight">

		<h3> Example </h3>

<ul class="nav nav-tabs">
  <li><a href="#xml" data-toggle="tab">XML</a></li>
  <li><a href="#json" data-toggle="tab">JSON</a></li>
</ul>
<div class="tab-content">
  <div class="tab-pane active" id="xml">
		Sample Request	
			<pre class="headers">
				<code>
					<%= meth.sample_request_xml %>
				</code>
			</pre>
		
		Sample Response 
			<pre>
				<code class="bash">
					<%= meth.sample_response_xml %>
				</code>
			</pre>

  </div>
  <div class="tab-pane" id="json">
		Sample Request	
			<pre class="headers">
				<code>
					<%= meth.sample_request_json %>
				</code>
			</pre>
		
		Sample Response 
			<pre>
				<code class="bash">
					<%= meth.sample_response_json %>
				</code>
			</pre>
  </div>
</div>

	


		</div>


	</article>
<% end %>

app/views/apidog/api/page.html.erb
<h1>Api#page</h1>
<p>Find me in app/views/apidog/api/page.html.erb</p>

app/views/layouts/apidog/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= @api.brand %> API Docs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <%= stylesheet_link_tag    "apidog/application", :media => "all" %>


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>


<div id="wrapper">
    <div class="container-fluid">
    	<div class="masthead">

        <h3 class="muted"><%= @api.brand %>, <%= @api.title %></h3>
      </div>
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
      		<% @api.categories.each do |category| %>
      		  
      		<li class="nav-header"><%= category.name %></li>
      		  <% category.objizzles.each do |object| %>
	              <li><%= link_to  object.name, apidog_object_path(@api.title,object)  %></li>
      		  <% end %>
      		<% end %>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
			<%= yield %>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; <%= @api.brand %> 2013</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
</div>
  <%= javascript_include_tag "apidog/application" %>
  </body>
</html>